# Домашняя работа. Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [73]:
import numpy as np
print (np.__version__)

1.23.5


2) Создать нулевой вектор размера 10

In [ ]:
arr = np.zeros(10)

3) Создать вектор заполненный 7-ами размера 7

In [ ]:
np.full((7), 7)

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [ ]:
np.arange(10,101)[::2]

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [ ]:
np.random.random_sample(10)[::-1]

array([0.68133134, 0.07892476, 0.54134449, 0.02463444, 0.31691169,
       0.42049616, 0.8995651 , 0.76473248, 0.39129959, 0.37724126])

6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [ ]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [ ]:
np.eye(4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [ ]:
arr = np.full((4,4),7)
np.fill_diagonal(arr, [1,2,3,4])
print(arr)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [ ]:
np.full((5,5),[0,1,2,3,4])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [ ]:
matrix = np.random.random_sample((10,10))
matrix_mean = matrix - matrix.mean(axis = 1, keepdims=True)
matrix_mean

array([[-0.30888361,  0.25938385,  0.25689061,  0.33603576, -0.1087439 ,
         0.1940388 , -0.39610055,  0.15202867, -0.12837896, -0.25627065],
       [-0.38881852,  0.06519389, -0.1337044 ,  0.35090589,  0.23083003,
         0.20224917, -0.3215942 ,  0.38290177, -0.04881622, -0.33914742],
       [ 0.32552324,  0.0023519 ,  0.09570033,  0.26337979, -0.03656439,
        -0.20367326, -0.41359541,  0.28859608, -0.33270237,  0.01098409],
       [-0.34848639, -0.13103316,  0.1966713 ,  0.09063679, -0.0608489 ,
        -0.0189387 , -0.22471743,  0.2072442 ,  0.03366265,  0.25580965],
       [-0.20361176,  0.26679145,  0.23007517,  0.1522291 , -0.28681007,
        -0.27405572, -0.33162997,  0.23652548,  0.12533675,  0.08514957],
       [-0.32249617,  0.24725506,  0.38832018,  0.06389509,  0.32708788,
        -0.37932832, -0.0225197 , -0.21302813,  0.04009028, -0.12927618],
       [-0.02394033,  0.32294176, -0.0199305 , -0.52331423,  0.0116842 ,
         0.09536932,  0.17169568,  0.02403105

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
martix = np.random.random_sample((10,10))
matrix_median = matrix - np.median(matrix,axis = 0,keepdims=True)
matrix_median

array([[-0.43401789,  0.60241672,  0.12954493,  0.03058172,  0.67469096,
         0.16723439,  0.16549938,  0.16723439,  0.16549938],
       [ 0.        , -0.35286159,  0.        , -0.15505096, -0.14461048,
        -0.13933088, -0.06214303, -0.13933088, -0.06214303],
       [ 0.08653529,  0.        , -0.63865976,  0.42200029,  0.        ,
         0.17341657, -0.04059102,  0.17341657, -0.04059102],
       [ 0.13933088,  0.33912481, -0.19877592, -0.39993914, -0.23139158,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-0.23766693, -0.26036539,  0.13264704,  0.        ,  0.14673111,
        -0.00813236,  0.03035317, -0.00813236,  0.03035317]])

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [ ]:
matrix = np.random.random_sample((5,5))
matrix = np.concatenate((arr,arr.max(axis =1,keepdims=True),arr.min(axis =1,keepdims=True)),axis = 1)
print(arr)

[[0.23983404 0.96746994 0.80194834 0.59518082 0.9804172  0.9804172
  0.23983404]
 [0.67385193 0.01219163 0.67240341 0.40954814 0.16111577 0.67385193
  0.01219163]
 [0.76038722 0.36505323 0.03374365 0.98659938 0.30572625 0.98659938
  0.03374365]
 [0.81318281 0.70417804 0.47362749 0.16465996 0.07433467 0.81318281
  0.07433467]
 [0.43618501 0.10468784 0.80505045 0.5645991  0.45245736 0.80505045
  0.10468784]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [94]:
m1 = np.mat(np.arange(1, 50)[1::2].reshape(4,6))
print(m1)
m2 = np.mat(np.arange(1, 50)[2::2].reshape(6,4))
print(m2)
m3 = m1*m2
print(m3)
m = np.linalg.inv(m3)
print(m)

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]
 [38 40 42 44 46 48]]
[[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]
 [35 37 39 41]
 [43 45 47 49]]
[[1246 1330 1414 1498]
 [2902 3130 3358 3586]
 [4558 4930 5302 5674]
 [6214 6730 7246 7762]]
[[-3.66503876e+11  3.21853878e-04  1.09951163e+12 -7.33007752e+11]
 [-7.33007752e+11  2.19902326e+12 -2.19902326e+12  7.33007752e+11]
 [ 2.56552713e+12 -4.39804651e+12  1.09951163e+12  7.33007752e+11]
 [-1.46601550e+12  2.19902326e+12  0.00000000e+00 -7.33007752e+11]]


14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [ ]:
matrix = np.ones((3,3))
matrix = np.zeros((8,8),dtype=int)
matrix[1::2,::2] = 1
matrix[::2,1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
